version: '3.1'

name: json-schema-sql-builder
services:
  db:
    container_name: json-schema-sql-builder-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  phpmyadmin:
    container_name: json-schema-sql-builder-phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - db
  web:
    container_name: json-schema-sql-builder-web
    build: 
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - db